### PR TITLE
added outputResults() method

### PR DESCRIPTION
**Pull request by just44play**
New method that prints output on the screen. Also implemented a method getLaneStatus() to convert Status to std::string to make the output more explicit.

### CODE REVIEW

**Comment by just44play** [comment]
Score is 20, because there's no method that counts score yet.

**Comment by just44play** [comment]
I will provide some tests for gameLaneStatus(), PLEASE DON'T MERGE IT YET

**Comment by LordLukin** [comment]
Yep, tests are missing, so we are waiting for them.
Why haven't you worked in TDD? :)

**Comment by just44play** [comment]
I had difficulties with running input files. I'm still working on it :)

**Comment by just44play** [comment]
All tests are already provided, pull request is ready to merge

**Comment by just44play** [comment]
Checks are failing due to different order of input from files. Test passes locally.

**Comment by AndrzejBarecki** [comment]
OK

**Pull request merged**
